### ISSUE TITLE
Tweets from GetSearch are still being truncated

### ISSUE THREAD

**Issue by Flyer4109** [bear/python-twitter#537]
I am using GetSearch and the tweets are still being truncated even though I am using `tweet_mode="extended"` and `full_text`. Below is the code I am using and the output.

```python
api = twitter.Api(consumer_token, consumer_secret, access_token, access_token_secret, tweet_mode="extended")

tweets = api.GetSearch(term="#gameofthrones", lang="en", count=100)

for tweet in tweets:
    print(tweet.full_text)
```
Example of truncated tweet:
`RT @kimrrenfro: #GameofThrones star Maisie Williams said the eighth and final season is planned for April 2019 (which makes a lot of sense!…`
 
Should be:
`RT @kimrrenfro: #GameofThrones star Maisie Williams said the eighth and final season is planned for April 2019 (which makes a lot of sense!) https://t.co/l7dmg1pfFT`

**Comment by Flyer4109** [comment]
Turns out it was only retweets and i have fixed it, nevermind.

**Comment by comgra** [comment]
@Flyer4109 hi, i also add "tweet_mode="extended"" in Api, but still get truncated, how did you fix it? thanks.

**Comment by Flyer4109** [comment]
@comgra Hi, you need to add `tweet_mode=extended` to the API and whenever replace `.text` with `.full_text`. This should get the full version of the tweets unless they are retweets. Retweets have `RT @<username>: ` at the beginning and these sometimes get truncated. To solve this check if `.retweeted_status` exists, if it does then you need to use `.retweeted_status.full_text`. Below is an example of my working code:

```python
api = twitter.Api(consumer_token, consumer_secret, access_token, access_token_secret, tweet_mode="extended")

tweets = api.GetSearch(term="#gameofthrones", lang="en", count=100)

for tweet in tweets:
    if tweet.retweeted_status is None:
        print(tweet.full_text)
    else:
        print(tweet.retweeted_status.full_text)
```

Hope this helps!
